spring:
  application:
    name: BotC
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9092

server:
  servlet:
    context-path: /api

frontend:
  cors:
    origin:
  url:

jwt:
  secret: secrettsdfgdsfg
  token:
    validity:
      time: 2592000

kafka:
  topics:
    notification: notificationtopic
    channels: channelstopic
    channels-response: channelsresponsetopic

discord:
  clientId:
  secret:
  token-url:
  user-url:
  redirect-uri:

listen:
  auto:
    start: true