spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: false
  kafka:
#    bootstrap-servers: botc-kafka:9092
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}:${KAFKA_BOOTSTRAP_PORT}
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST}
      port: 27017
      database: ${SPRING_DATA_MONGODB_DATABASE}
      username: ${SPRING_DATA_MONGODB_USERNAME}
      password: ${SPRING_DATA_MONGODB_PASSWORD}
      authentication-database: admin

frontend:
  cors:
    origin: ${FRONTEND_CORS_ORIGIN}
  url: ${FRONTEND_URL}

jwt:
  secret: ${JWT_SECRET}
  token:
    validity:
      time: 2592000

discord:
  clientId: ${DISCORD_CLIENT_ID}
  secret: ${DISCORD_SECRET}
  token-url: ${DISCORD_TOKEN_URL}
  user-url: ${DISCORD_USER_URL}
  redirect-uri: ${DISCORD_REDIRECT_URL}