spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;IGNORECASE=TRUE
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /guest/h2-console
  sql:
    init:
      data-locations: classpath:data2-local.sql
  kafka:
    bootstrap-servers: localhost:9092
  data:
    mongodb:
      host: localhost
      port: 27017
      database: botc
      username:
      password:
      authentication-database: admin

frontend:
  cors:
    origin: "*"
  url: http://192.168.1.30:4200

jwt:
  secret: secrettttttttttttttttttttttttttttttttttttttttt
  token:
    validity:
      time: 7200

discord:
  clientId: 1369101839831797811
  secret: V0vNV3dSpIGcZwsyFrzfD5Qwbp-Gazey
  token-url: https://discord.com/api/oauth2/token
  user-url: https://discord.com/api/users/@me
  redirect-uri: http://192.168.1.30:4200/welcome
#  redirect-uri: http://83.10.241.97:44444/welcome

de:
  flapdoodle:
    mongodb:
      port: 27018
      embedded:
        version: 7.0.0