spring:
  application:
    name: BotC
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      
frontend-url:

jwt:
  secret: secrettsdfgdsfg
  token:
    validity:
      time: 2592000