spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /guest/h2-console
  sql:
    init:
#      data-locations: classpath:data-local.sql
      data-locations: classpath:data2-local.sql
  kafka:
    bootstrap-servers: localhost:9092

frontend:
  cors:
    origin: "*"
  url: http://localhost:4200

jwt:
  secret: secrettttttttttttttttttttttttttttttttttttttttt
  token:
    validity:
      time: 3000

discord:
  clientId: 1369101839831797811
  secret: 1Cwhsc-i3oHJmu-h7cYO_ys1-ronC9WS
  token-url: https://discord.com/api/oauth2/token
  user-url: https://discord.com/api/users/@me
  redirect-uri: http://localhost:4200/welcome
#  redirect-uri: http://83.10.241.97:44444/welcome