package com.czachodym.BotC.service;

import com.czachodym.BotC.dao.CharacterRepository;
import com.czachodym.BotC.dao.GroupRepository;
import com.czachodym.BotC.dao.ScriptRepository;
import com.czachodym.BotC.dto.GroupDto;
import com.czachodym.BotC.dto.UserDto;
import com.czachodym.BotC.exception.EntityAlreadyExistsException;
import com.czachodym.BotC.model.Alignment;
import com.czachodym.BotC.model.Character;
import com.czachodym.BotC.model.Group;
import com.czachodym.BotC.model.Script;
import com.czachodym.BotC.model.util.ScriptCharacter;
import com.czachodym.BotC.service.util.DtoMapper;
import com.czachodym.BotC.service.util.Validators;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.util.StreamUtils;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.*;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.concurrent.atomic.AtomicLong;

@Service
@RequiredArgsConstructor
@Slf4j
public class GroupService {
    private final String CHARACTER_IMAGES_DIR = "character_images";
    private final Path root = Paths.get(CHARACTER_IMAGES_DIR);
    private final GroupRepository groupRepository;
    private final CharacterRepository characterRepository;
    private final ScriptRepository scriptRepository;
    private final DtoMapper dtoMapper;
    private final Validators validators;

    public List<GroupDto> getAllGroups(){
        log.info("Getting all groups");
        List<Group> groups = groupRepository.findAll();
        log.info("Groups found.");
        return dtoMapper.mapGroup(groups);
    }

    public Group createGroup(String name){
        boolean exists = groupRepository.existsByName(name);
        if(exists) {
            throw new EntityAlreadyExistsException(name);
        }
        Group group = Group.builder()
                .name(name)
                .build();
        log.info("Saving group.");
        Group savedGroup = groupRepository.save(group);
        log.info("Group saved, generating charactes.");
        List<Character> characters = characterRepository.saveAll(generateCharacters(savedGroup));
        copyImages(group.getId(), characters.get(0).getId());
        log.info("Characters saved, generating scripts.");
        List<Script> scripts = scriptRepository.saveAll(generateScripts(savedGroup, characters));
        log.info("Scripts saved. Group created successfully.");
        return group;
    }

    private void copyImages(long groupId, long firstId){
        Path basePath = root.resolve("base_character_images"); // e.g., .../character_images/base_character_images
        Path newPath  = root.resolve(Long.toString(groupId));  // e.g., .../character_images/3

        try {
            Files.createDirectories(newPath); // no-op if it already exists

            for (String dirName : List.of("30", "100", "orig")) {
                Path source = basePath.resolve(dirName);
                Path target = newPath.resolve(dirName);
                copyDirectoryRecursively(source, target, firstId);
            }
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    private static void copyDirectoryRecursively(Path source, Path target, long firstId) throws IOException {
        if (!Files.exists(source)) return;

        Files.walkFileTree(source, new SimpleFileVisitor<>() {
            @Override
            public FileVisitResult preVisitDirectory(Path dir, BasicFileAttributes attrs) throws IOException {
                Path rel  = source.relativize(dir);
                Path dest = target.resolve(rel);
                Files.createDirectories(dest);
                return FileVisitResult.CONTINUE;
            }

            @Override
            public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IOException {
                Path rel  = source.relativize(file);

                // Original filename
                String fileName = file.getFileName().toString();
                long oldId = Long.parseLong(fileName.split("\\.")[0]);

                // Example renaming: prefix with group id
                String newFileName = (oldId + firstId - 1) + ".png";

                Path dest;
                if (rel.getParent() == null) {
                    // No parent directory → place file directly in target
                    dest = target.resolve(newFileName);
                } else {
                    // Keep subdirectory structure → put renamed file inside
                    dest = target.resolve(rel.getParent()).resolve(newFileName);
                }

                Files.copy(file, dest,
                        StandardCopyOption.REPLACE_EXISTING,
                        StandardCopyOption.COPY_ATTRIBUTES);
                return FileVisitResult.CONTINUE;
            }
        });
    }

    private List<Script> generateScripts(Group group, List<Character> characters){
        List<Script> scripts = new ArrayList<>();

        List<ScriptCharacter> tbScriptCharacters = new ArrayList<>(22);
        for(int i = 0; i < 22; i++){
            tbScriptCharacters.add(ScriptCharacter.builder()
                    .characterOrder(i)
                    .character(characters.get(i))
                    .build());
        }
        List<ScriptCharacter> bmrScriptCharacters = new ArrayList<>(25);
        for(int i = 0; i < 25; i++){
            bmrScriptCharacters.add(ScriptCharacter.builder()
                    .characterOrder(i)
                    .character(characters.get(i + 22))
                    .build());
        }
        List<ScriptCharacter> svScriptCharacters = new ArrayList<>(25);
        for(int i = 0; i < 25; i++){
            svScriptCharacters.add(ScriptCharacter.builder()
                    .characterOrder(i)
                    .character(characters.get(i + 47))
                    .build());
        }

        scripts.add(Script.builder()
                .groups(Set.of(group))
                .name("Trouble Brewing")
                .author("The Pandemonium Institute")
                .scriptCharacters(tbScriptCharacters)
                .build());

        scripts.add(Script.builder()
                .groups(Set.of(group))
                .name("Bad Moon Rising")
                .author("The Pandemonium Institute")
                .scriptCharacters(bmrScriptCharacters)
                .build());

        scripts.add(Script.builder()
                .groups(Set.of(group))
                .name("Sects & Violets")
                .author("The Pandemonium Institute")
                .scriptCharacters(svScriptCharacters)
                .build());

        return scripts;
    }

    private List<Character> generateCharacters(Group group){
        List<Character> characters = new ArrayList<>();

        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Washerwoman")
                .alignment(Alignment.Townsfolk)
                .description("You start knowing that 1 of 2 players is a particular Townsfolk.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Washerwoman")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Librarian")
                .alignment(Alignment.Townsfolk)
                .description("You start knowing that 1 of 2 players is a particular Outsider, or that zero are in play.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Librarian")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Investigator")
                .alignment(Alignment.Townsfolk)
                .description("You start knowing that 1 of 2 players is players particular Minion.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Investigator")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Chef")
                .alignment(Alignment.Townsfolk)
                .description("You start knowing how many pairs of evil players there are.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Chef")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Empath")
                .alignment(Alignment.Townsfolk)
                .description("Each night, you learn how many of your 2 alive neighbors are evil.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Empath")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Fortune Teller")
                .alignment(Alignment.Townsfolk)
                .description("Each night, choose 2 players: you learn if either is a Demon. There is a good player that always registers as a Demon to you.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Fortune_Teller")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Undertaker")
                .alignment(Alignment.Townsfolk)
                .description("Each night*, you learn which character died by execution today.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Undertaker")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Monk")
                .alignment(Alignment.Townsfolk)
                .description("Each night*, choose a player (not yourself): they are safe from the Demon tonight.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Monk")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Ravenkeeper")
                .alignment(Alignment.Townsfolk)
                .description("If you die at night, you are woken to choose a player: you learn their character.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Ravenkeeper")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Virgin")
                .alignment(Alignment.Townsfolk)
                .description("The first time you are nominated, if the nominator is a Townsfolk, they are executed immediately.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Virgin")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Slayer")
                .alignment(Alignment.Townsfolk)
                .description("Once per game, during the day, publicly choose a player: if they are the Demon, they die.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Slayer")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Soldier")
                .alignment(Alignment.Townsfolk)
                .description("You are safe from the Demon.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Soldier")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Mayor")
                .alignment(Alignment.Townsfolk)
                .description("If only 3 players live & no execution occurs, your team wins. If you die at night, another player might die instead.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Mayor")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Butler")
                .alignment(Alignment.Outsider)
                .description("Each night, choose a player (not yourself): tomorrow, you may only vote if they are voting too.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Butler")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Drunk")
                .alignment(Alignment.Outsider)
                .description("You do not know you are the Drunk. You think you are a Townsfolk character, but you are not.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Drunk")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Recluse")
                .alignment(Alignment.Outsider)
                .description("You might register as evil & as a Minion or Demon, even if dead.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Recluse")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Saint")
                .alignment(Alignment.Outsider)
                .description("If you die by execution, your team loses.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Saint")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Poisoner")
                .alignment(Alignment.Minion)
                .description("Each night, choose a player: they are poisoned tonight and tomorrow day.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Poisoner")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Spy")
                .alignment(Alignment.Minion)
                .description("Each night, you see the Grimoire. You might register as good & as a Townsfolk or Outsider, even if dead.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Spy")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Baron")
                .alignment(Alignment.Minion)
                .description("There are 2 extra Outsiders in play.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Baron")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Scarlet Woman")
                .alignment(Alignment.Minion)
                .description("If there are 5 or more players alive & the Demon dies, you become the Demon. (Travellers don't count)")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Scarlet_Woman")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Imp")
                .alignment(Alignment.Demon)
                .description("Each night*, choose a player: they die. If you kill yourself this way, a Minion becomes the Imp.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Imp")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Grandmother")
                .alignment(Alignment.Townsfolk)
                .description("You start knowing a good player & their character. If the Demon kills them, you die too.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Grandmother")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Sailor")
                .alignment(Alignment.Townsfolk)
                .description("Each night, choose an alive player: either you or they are drunk until dusk. You can't die.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Sailor")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Chambermaid")
                .alignment(Alignment.Townsfolk)
                .description("Each night, choose 2 alive players (not yourself): you learn how many woke tonight  due to their ability.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Chambermaid")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Exorcist")
                .alignment(Alignment.Townsfolk)
                .description("Each night*, choose a player (different to last night): the Demon, if chosen, learns who you are then doesn't wake tonight")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Exorcist")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Innkeeper")
                .alignment(Alignment.Townsfolk)
                .description("Each night*, choose 2 players: they can't die tonight, but 1 is drunk until dusk.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Innkeeper")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Gambler")
                .alignment(Alignment.Townsfolk)
                .description("Each night*, choose a player & guess their character: if you guess wrong, you die.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Gambler")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Gossip")
                .alignment(Alignment.Townsfolk)
                .description("Each day, you may make a public statement. Tonight, if it was true, a player dies.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Gossip")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Courtier")
                .alignment(Alignment.Townsfolk)
                .description("Once per game, at night, choose a character: they are drunk for 3 nights & 3 days.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Courtier")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Professor")
                .alignment(Alignment.Townsfolk)
                .description("Once per game, at night*, choose a dead player: if they are a Townsfolk, they are resurrected.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Professor")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Minstrel")
                .alignment(Alignment.Townsfolk)
                .description("When a Minion dies by execution, all other players (except Travellers) are drunk until dusk tomorrow.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Minstrel")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Tea Lady")
                .alignment(Alignment.Townsfolk)
                .description("If both your alive neighbors are good, they can't die.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Tea_Lady")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Pacifist")
                .alignment(Alignment.Townsfolk)
                .description("Executed good players might not die.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Pacifist")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Fool")
                .alignment(Alignment.Townsfolk)
                .description("The 1st time you die, you don't.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Fool")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Goon")
                .alignment(Alignment.Outsider)
                .description("Each night, the 1st player to choose you with their ability is drunk until dusk. You become their alignment.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Goon")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Lunatic")
                .alignment(Alignment.Outsider)
                .description("You think you are a Demon, but you are not. The Demon knows who you are & who you choose at night.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Lunatic")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Tinker")
                .alignment(Alignment.Outsider)
                .description("You might die at any time.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Tinker")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Moonchild")
                .alignment(Alignment.Outsider)
                .description("When you learn that you died, publicly choose 1 alive player. Tonight, if it was a good player, they die.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Moonchild")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Godfather")
                .alignment(Alignment.Minion)
                .description("You start knowing which Outsiders are in play. If 1 died today, choose a player tonight: they die. [-1 or +1 Outsider]")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Godfather")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Assassin")
                .alignment(Alignment.Minion)
                .description("Once per game, at night*, choose a player: they die, even if for some reason they could not.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Assassin")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Devil's advocate")
                .alignment(Alignment.Minion)
                .description("Each night, choose a living player (different to last night): if executed tomorrow, they don't die.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Devil%27s_Advocate")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Mastermind")
                .alignment(Alignment.Minion)
                .description("If the Demon dies by execution (ending the game,null), play for 1 more day. If a player is then executed, their team loses.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Mastermind")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Zombuul")
                .alignment(Alignment.Demon)
                .description("Each night*, if no-one died today, choose a player: they die. The 1st time you die, you live but register as dead.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Zombuul")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Pukka")
                .alignment(Alignment.Demon)
                .description("Each night, choose a player: they are poisoned. The previously poisoned player dies then becomes healthy.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Pukka")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Shabaloth")
                .alignment(Alignment.Demon)
                .description("Each night*, choose 2 players: they die. A dead player you chose last night might be regurgitated.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Shabaloth")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Po")
                .alignment(Alignment.Demon)
                .description("Each night*, you may choose a player: they die. If your last choice was no-one, choose 3 players tonight.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Po")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Clockmaker")
                .alignment(Alignment.Townsfolk)
                .description("You start knowing how many steps from the Demon to its nearest Minion.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Clockmaker")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Dreamer")
                .alignment(Alignment.Townsfolk)
                .description("Each night, choose a player (not yourself or Travellers): you learn 1 good & 1 evil character, 1 of which is correct.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Dreamer")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Snake Charmer")
                .alignment(Alignment.Townsfolk)
                .description("Each night, choose an alive player: a chosen Demon swaps characters & alignments with you & is then poisoned.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Snake_Charmer")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Mathematician")
                .alignment(Alignment.Townsfolk)
                .description("Each night, you learn how many players' abilities worked abnormally (since dawn) due to another character's ability.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Mathematician")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Flowergirl")
                .alignment(Alignment.Townsfolk)
                .description("Each night*, you learn if a Demon voted today.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Flowergirl")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Town Crier")
                .alignment(Alignment.Townsfolk)
                .description("Each night*, you learn if a Minion nominated today.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Town_Crier")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Oracle")
                .alignment(Alignment.Townsfolk)
                .description("Each night*, you learn how many dead players are evil.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Oracle")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Savant")
                .alignment(Alignment.Townsfolk)
                .description("Each day, you may visit the Storyteller to learn 2 things in private: 1 is true & 1 is false.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Savant")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Seamstress")
                .alignment(Alignment.Townsfolk)
                .description("Once per game, at night, choose 2 players (not yourself): you learn if they are the same alignment.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Seamstress")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Philosopher")
                .alignment(Alignment.Townsfolk)
                .description("Once per game, at night, choose a good character: gain that ability. If this character is in play, they are drunk.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Philosopher")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Artist")
                .alignment(Alignment.Townsfolk)
                .description("Once per game, during the day, privately ask the Storyteller any yes/no question.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Artist")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Juggler")
                .alignment(Alignment.Townsfolk)
                .description("On your 1st day, publicly guess up to 5 players' characters. That night, you learn how many you got correct.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Juggler")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Sage")
                .alignment(Alignment.Townsfolk)
                .description("If the Demon kills you, you learn that it is 1 of 2 players.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Sage")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Mutant")
                .alignment(Alignment.Outsider)
                .description("If you are \"mad\" about being an Outsider, you might be executed.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Mutant")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Sweetheart")
                .alignment(Alignment.Outsider)
                .description("When you die, 1 player is drunk from now on.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Sweetheart")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Barber")
                .alignment(Alignment.Outsider)
                .description("If you died today or tonight, the Demon may choose 2 players (not another Demon) to swap characters.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Barber")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Klutz")
                .alignment(Alignment.Outsider)
                .description("When you learn that you died, publicly choose 1 alive player: if they are evil, your team loses.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Klutz")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Evil Twin")
                .alignment(Alignment.Minion)
                .description("You & an opposing player know each other. If the good player is executed, evil wins. Good can't win if you both live.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Evil_Twin")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Witch")
                .alignment(Alignment.Minion)
                .description("Each night, choose a player: if they nominate tomorrow, they die. If just 3 players live, you lose this ability.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Witch")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Cerenovus")
                .alignment(Alignment.Minion)
                .description("Each night, choose a player & a good character: they are \"mad\" they are this character tomorrow, or might be executed.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Cerenovus")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Pit-Hag")
                .alignment(Alignment.Minion)
                .description("Each night*, choose a player & a character they become (if not in play). If a Demon is made, deaths tonight are arbitrary.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Pit-Hag")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Fang Gu")
                .alignment(Alignment.Demon)
                .description("Each night*, choose a player: they die. The 1st Outsider this kills becomes an evil Fang Gu & you die instead. [+1 Outsider]")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Fang_Gu")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Vigormortis")
                .alignment(Alignment.Demon)
                .description("Each night*, choose a player: they die. Minions you kill keep their ability & poison 1 Townsfolk neighbor. [-1 Outsider]")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Vigormortis")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("No Dashii")
                .alignment(Alignment.Demon)
                .description("Each night*, choose a player: they die. Your 2 Townsfolk neighbors are poisoned.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/No_Dashii")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Vortox")
                .alignment(Alignment.Demon)
                .description("Each night*, choose a player: they die. Townsfolk abilities yield false info. Each day, if no-one is executed, evil wins.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Vortox")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Acrobat")
                .alignment(Alignment.Townsfolk)
                .description("Each night*, choose a player: if they are or become drunk or poisoned tonight, you die.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Acrobat")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Alchemist")
                .alignment(Alignment.Townsfolk)
                .description("You have a Minion ability. When using this, the Storyteller may prompt you to choose differently.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Alchemist")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Alsaahir")
                .alignment(Alignment.Townsfolk)
                .description("Each day, if you publicly guess which players are Minion(s) and which are Demon(s,null), good wins.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Alsaahir")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Amnesiac")
                .alignment(Alignment.Townsfolk)
                .description("You do not know what your ability is. Each day, privately guess what it is: you learn how accurate you are.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Amnesiac")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Atheist")
                .alignment(Alignment.Townsfolk)
                .description("The Storyteller can break the game rules, and if executed, good wins, even if you are dead. [No evil characters]")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Atheist")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Balloonist")
                .alignment(Alignment.Townsfolk)
                .description("Each night, you learn a player of a different character type than last night. [+0 or +1 Outsider]")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Balloonist")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Banshee")
                .alignment(Alignment.Townsfolk)
                .description("If the Demon kills you, all players learn this. From now on, you may nominate twice per day and vote twice per nomination.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Banshee")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Bounty Hunter")
                .alignment(Alignment.Townsfolk)
                .description("You start knowing 1 evil player. If the player you know dies, you learn another evil player tonight. [1 Townsfolk is evil]")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Bounty_Hunter")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Cannibal")
                .alignment(Alignment.Townsfolk)
                .description("You have the ability of the recently killed executee. If they are evil, you are poisoned until a good player dies by execution.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Cannibal")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Choirboy")
                .alignment(Alignment.Townsfolk)
                .description("If the Demon kills the King, you learn which player is the Demon. [+the King]")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Choirboy")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Cult Leader")
                .alignment(Alignment.Townsfolk)
                .description("Each night, you become the alignment of an alive neighbor. If all good players choose to join your cult, your team wins.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Cult_Leader")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Engineer")
                .alignment(Alignment.Townsfolk)
                .description("Once per game, at night, choose which Minions or which Demon is in play.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Engineer")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Farmer")
                .alignment(Alignment.Townsfolk)
                .description("When you die at night, an alive good player becomes a Farmer.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Farmer")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Fisherman")
                .alignment(Alignment.Townsfolk)
                .description("Once per game, during the day, visit the Storyteller for some advice to help your team win.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Fisherman")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("General")
                .alignment(Alignment.Townsfolk)
                .description("Each night, you learn which alignment the Storyteller believes is winning: good, evil, or neither.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/General")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("High Priestess")
                .alignment(Alignment.Townsfolk)
                .description("Each night, learn which player the Storyteller believes you should talk to most.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/High_Priestess")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Huntsman")
                .alignment(Alignment.Townsfolk)
                .description("Once per game, at night, choose a living player: the Damsel, if chosen, becomes a not-in-play Townsfolk. [+the Damsel]")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Huntsman")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("King")
                .alignment(Alignment.Townsfolk)
                .description("Each night, if the dead equal or outnumber the living, you learn 1 alive character. The Demon knows you are the King.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/King")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Knight")
                .alignment(Alignment.Townsfolk)
                .description("You start knowing 2 players that are not the Demon.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Knight")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Lycanthrope")
                .alignment(Alignment.Townsfolk)
                .description("Each night*, choose an alive player. If good, they die & the Demon doesn’t kill tonight. One good player registers as evil.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Lycanthrope")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Magician")
                .alignment(Alignment.Townsfolk)
                .description("The Demon thinks you are a Minion. Minions think you are a Demon.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Magician")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Nightwatchman")
                .alignment(Alignment.Townsfolk)
                .description("Once per game, at night, choose a player: they learn you are the Nightwatchman.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Nightwatchman")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Noble")
                .alignment(Alignment.Townsfolk)
                .description("You start knowing 3 players, 1 and only 1 of which is evil.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Noble")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Pixie")
                .alignment(Alignment.Townsfolk)
                .description("You start knowing 1 in-play Townsfolk. If you were mad that you were this character, you gain their ability when they die.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Pixie")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Poppy Grower")
                .alignment(Alignment.Townsfolk)
                .description("Minions & Demons do not know each other. If you die, they learn who each other are that night.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Poppy_Grower")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Preacher")
                .alignment(Alignment.Townsfolk)
                .description("Each night, choose a player: a Minion, if chosen, learns this. All chosen Minions have no ability.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Preacher")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Shugenja")
                .alignment(Alignment.Townsfolk)
                .description("You start knowing if your closest evil player is clockwise or anti-clockwise. If equidistant, this info is arbitrary.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Shugenja")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Steward")
                .alignment(Alignment.Townsfolk)
                .description("You start knowing 1 good player.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Steward")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Village Idiot")
                .alignment(Alignment.Townsfolk)
                .description("Each night, choose a player: you learn their alignment. [+0 to +2 Village Idiots. 1 of the extras is drunk]")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Village_Idiot")
                .maxStartNumber(3)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Princess")
                .alignment(Alignment.Townsfolk)
                .description("On your 1st day, if you nominated & executed a player, the Demon doesn’t kill tonight.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Princess")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Damsel")
                .alignment(Alignment.Outsider)
                .description("All Minions know a Damsel is in play. If a Minion publicly guesses you (once,null), your team loses.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Damsel")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Golem")
                .alignment(Alignment.Outsider)
                .description("You may only nominate once per game. When you do, if the nominee is not the Demon, they die.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Golem")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Hatter")
                .alignment(Alignment.Outsider)
                .description("If you died today or tonight, the Minion & Demon players may choose new Minion & Demon characters to be.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Hatter")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Heretic")
                .alignment(Alignment.Outsider)
                .description("Whoever wins, loses & whoever loses, wins, even if you are dead.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Heretic")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Ogre")
                .alignment(Alignment.Outsider)
                .description("On your 1st night, choose a player (not yourself): you become their alignment (you don't know which) even if drunk or poisoned.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Ogre")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Plague Doctor")
                .alignment(Alignment.Outsider)
                .description("When you die, the Storyteller gains a Minion ability.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Plague_Doctor")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Politician")
                .alignment(Alignment.Outsider)
                .description("If you were the player most responsible for your team losing, you change alignment & win, even if dead.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Politician")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Puzzlemaster")
                .alignment(Alignment.Outsider)
                .description("1 player is drunk, even if you die. If you guess (once) who it is, learn the Demon player, but guess wrong & get false info.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Puzzlemaster")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Snitch")
                .alignment(Alignment.Outsider)
                .description("Each Minion gets 3 bluffs.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Snitch")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Zealot")
                .alignment(Alignment.Outsider)
                .description("If there are 5 or more players alive, you must vote for every nomination.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Zealot")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Hermit")
                .alignment(Alignment.Outsider)
                .description("You have all Outsider abilities. [-0 or -1 Outsider]")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Hermit")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Boffin")
                .alignment(Alignment.Minion)
                .description("The Demon (even if drunk or poisoned) has a not-in-play good character's ability. You both know which.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Boffin")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Boomdandy")
                .alignment(Alignment.Minion)
                .description("If you are executed, all but 3 players die. After a 10 to 1 countdown, the player with the most players pointing at them, dies.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Boomdandy")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Fearmonger")
                .alignment(Alignment.Minion)
                .description("Each night, choose a player: if you nominate & execute them, their team loses. All players know if you choose a new player.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Fearmonger")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Goblin")
                .alignment(Alignment.Minion)
                .description("If you publicly claim to be the Goblin when nominated & are executed that day, your team wins.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Goblin")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Harpy")
                .alignment(Alignment.Minion)
                .description("Each night, choose 2 players: tomorrow, the 1st player is mad that the 2nd is evil, or one or both might die.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Harpy")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Marionette")
                .alignment(Alignment.Minion)
                .description("You think you are a good character, but you are not. The Demon knows who you are. [You neighbor the Demon]")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Marionette")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Mezepheles")
                .alignment(Alignment.Minion)
                .description("You start knowing a secret word. The 1st good player to say this word becomes evil that night.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Mezepheles")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Organ Grinder")
                .alignment(Alignment.Minion)
                .description("All players keep their eyes closed when voting and the vote tally is secret. Each night, choose if you are drunk until dusk.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Organ_Grinder")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Psychopath")
                .alignment(Alignment.Minion)
                .description("Each day, before nominations, you may publicly choose a player: they die. If executed, you only die if you lose roshambo.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Psychopath")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Summoner")
                .alignment(Alignment.Minion)
                .description("You get 3 bluffs. On the 3rd night, choose a player: they become an evil Demon of your choice. [No Demon]")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Summoner")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Vizier")
                .alignment(Alignment.Minion)
                .description("All players know you are the Vizier. You cannot die during the day. If good voted, you may choose to execute immediately.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Vizier")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Widow")
                .alignment(Alignment.Minion)
                .description("On your first night, look at the Grimoire & choose a player: they are poisoned. 1 good player knows a Widow is in play.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Widow")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Wizard")
                .alignment(Alignment.Minion)
                .description("Once per game, choose to make a wish. If granted, it might have a price & leave a clue as to its nature.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Wizard")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Xaan")
                .alignment(Alignment.Minion)
                .description("On night X, all Townsfolk are poisoned until dusk. [X Outsiders]")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Xaan")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Wraith")
                .alignment(Alignment.Minion)
                .description("You may choose to open your eyes at night. You wake when other evil players do.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Wraith")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Al-Hadikhia")
                .alignment(Alignment.Demon)
                .description("Each night*, you may choose 3 players (all players learn who): each silently chooses to live or die, but if all live, all die.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Al-Hadikhia")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Kazali")
                .alignment(Alignment.Demon)
                .description("Each night*, choose a player: they die. [You choose which players are which Minions. -? to +? Outsiders]")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Kazali")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Legion")
                .alignment(Alignment.Demon)
                .description("Each night*, a player might die. Executions fail if only evil voted. You register as a Minion too. [Most players are Legion]")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Legion")
                .maxStartNumber(10)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Leviathan")
                .alignment(Alignment.Demon)
                .description("If more than 1 good player is executed, evil wins. All players know you are in play. After day 5, evil wins.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Leviathan")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Lil Monsta")
                .alignment(Alignment.Demon)
                .description("Each night, Minions choose who babysits Lil' Monsta & 'is the Demon'. Each night*, a player might die. [+1 Minion]")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Lil%27_Monsta")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Lleech")
                .alignment(Alignment.Demon)
                .description("Each night*, choose a player: they die. You start by choosing a player: they are poisoned. You die if & only if they are dead.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Lleech")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Lord of Typhon")
                .alignment(Alignment.Demon)
                .description("Each night*, choose a player: they die. [Evil characters are in a line. You are in the middle. +1 Minion. -? to +? Outsiders]")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Lord_of_Typhon")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Ojo")
                .alignment(Alignment.Demon)
                .description("Each night*, choose a character: they die. If they are not in play, the Storyteller chooses who dies.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Ojo")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Riot")
                .alignment(Alignment.Demon)
                .description("On day 3, Minions become Riot & nominees die but nominate an alive player immediately. This must happen.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Riot")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Yaggababble")
                .alignment(Alignment.Demon)
                .description("You start knowing a secret phrase. For each time you said it publicly today, a player might die.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Yaggababble")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Scapegoat")
                .alignment(Alignment.Traveller)
                .description("If a player of your alignment is executed, you might be executed instead.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Scapegoat")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Gunslinger")
                .alignment(Alignment.Traveller)
                .description("Each day, after the 1st vote has been tallied, you may choose a player that voted: they die.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Gunslinger")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Beggar")
                .alignment(Alignment.Traveller)
                .description("You must use a vote token to vote. If a dead player gives you theirs, you learn their alignment. You are sober and healthy.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Beggar")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Bureaucrat")
                .alignment(Alignment.Traveller)
                .description("Each night, choose a player (not yourself): their vote counts as 3 votes tomorrow.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Bureaucrat")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Thief")
                .alignment(Alignment.Traveller)
                .description("Each night, choose a player (not yourself): their vote counts negatively tomorrow.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Thief")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Butcher")
                .alignment(Alignment.Traveller)
                .description("Each day, after the 1st execution, you may nominate again.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Butcher")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Bone Collector")
                .alignment(Alignment.Traveller)
                .description("Once per game, at night*, choose a dead player: they regain their ability until dusk.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Bone_Collector")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Harlot")
                .alignment(Alignment.Traveller)
                .description("Each night*, choose a living player: if they agree, you learn their character, but you both might die.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Harlot")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Barista")
                .alignment(Alignment.Traveller)
                .description("Each night, until dusk, 2) a player becomes sober, healthy & gets true info, or 2) their ability works twice. They learn which.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Barista")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Deviant")
                .alignment(Alignment.Traveller)
                .description("If you were funny today, you cannot die by exile.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Deviant")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Apprentice")
                .alignment(Alignment.Traveller)
                .description("On your 1st night, you gain a Townsfolk ability (if good) or a Minion ability (if evil).")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Apprentice")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Matron")
                .alignment(Alignment.Traveller)
                .description("Each day, you may choose up to 3 sets of 2 players to swap seats. Players may not leave their seats to talk in private.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Matron")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Voudon")
                .alignment(Alignment.Traveller)
                .description("Only you & the dead can vote. They don't need a vote token to do so. A 50% majority isn't required.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Voudon")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Judge")
                .alignment(Alignment.Traveller)
                .description("Once per game, if another player nominated, you may choose to force the current execution to pass or fail.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Judge")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Bishop")
                .alignment(Alignment.Traveller)
                .description("Only the Storyteller can nominate. At least 1 opposing player must be nominated each day.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Bishop")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Gangster")
                .alignment(Alignment.Traveller)
                .description("Once per day, you may choose to kill an alive neighbor, if your other alive neighbor agrees.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Gangster")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Gnome")
                .alignment(Alignment.Traveller)
                .description("All players start knowing a player of your alignment. You may choose to kill anyone who nominates them.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Gnome")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Cacklejack")
                .alignment(Alignment.Traveller)
                .description("Each day, choose a player: a different player changes character tonight.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Cacklejack")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Doomsayer")
                .alignment(Alignment.Fabled)
                .description("If 4 or more players live, each living player may publicly choose (once per game) that a player of their own alignment dies.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Doomsayer")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Angel")
                .alignment(Alignment.Fabled)
                .description("Something bad might happen to whoever is most responsible for the death of a new player.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Angel")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Buddhist")
                .alignment(Alignment.Fabled)
                .description("For the first 2 minutes of each day, veteran players may not talk.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Buddhist")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Hell's Librarian")
                .alignment(Alignment.Fabled)
                .description("Something bad might happen to whoever talks when the Storyteller has asked for silence.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Hell's_Librarian")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Revolutionary")
                .alignment(Alignment.Fabled)
                .description("2 neighboring players are known to be the same alignment. Once per game, 1 of them registers falsely.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Revolutionary")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Fiddler")
                .alignment(Alignment.Fabled)
                .description("Once per game, the Demon secretly chooses an opposing player: all players choose which of these 2 players win.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Fiddler")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Toymaker")
                .alignment(Alignment.Fabled)
                .description("The Demon may choose not to attack & must do this at least once per game. Evil players get normal starting info.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Toymaker")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Fibbin")
                .alignment(Alignment.Fabled)
                .description("Once per game, 1 good player might get incorrect information.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Fibbin")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Duchess")
                .alignment(Alignment.Fabled)
                .description("Each day, 3 players may choose to visit you. At night*, each visitor learns how many visitors are evil, but 1 gets false info.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Duchess")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Sentinel")
                .alignment(Alignment.Fabled)
                .description("There might be 1 extra or 1 fewer Outsider in play.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Sentinel")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Spirit of Ivory")
                .alignment(Alignment.Fabled)
                .description("There can't be more than 1 extra evil player.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Spirit_of_Ivory")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Djinn")
                .alignment(Alignment.Fabled)
                .description("Use the Djinn's special rule. All players know what it is.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Djinn")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Bootlegger")
                .alignment(Alignment.Fabled)
                .description("This script has homebrew characters or rules.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Bootlegger")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Ferryman")
                .alignment(Alignment.Fabled)
                .description("On the final day, all dead players regain their vote token.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Ferryman")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Gardener")
                .alignment(Alignment.Fabled)
                .description("The Storyteller assigns 1 or more players' characters.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Gardener")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());
        characters.add(Character.builder()
                .groups(Set.of(group))
                .name("Storm Catcher")
                .alignment(Alignment.Fabled)
                .description("Name a good character. If in play, they can only die by execution, but evil players learn which player it is.")
                .linkToWiki("https://wiki.bloodontheclocktower.com/Storm_Catcher")
                .maxStartNumber(1)
                .tips(null)
                .imageUploaded(true)
                .build());

        return characters;
    }
}
